name: Daily New High Pipeline

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

env:
  # J-Quants APIの環境変数
  JQUANTS_API_KEY: ${{ secrets.JQUANTS_API_KEY }}

  # LINE Messaging APIの環境変数
  LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}

  # Cloudflare R2 APIの環境変数
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  R2_PUBLIC_DEV_ID: ${{ secrets.R2_PUBLIC_DEV_ID }}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run pipeline
        run: python main.py